### ISSUE TITLE
Design - Gap Diagram

### ISSUE THREAD

**Issue by grwim** [grwim/grwim.github.io#2]
Find 5-10 examples of diagrams, graphs, etc that 1) are visually strong and 2) communicate the idea that "something is missing" or "there's a gap" or etc...

**Comment by grwim** [comment]
Was able to find four such examples thus far:

1 - Similar to what we currently have, but represents the Gap differently 
https://mk0blogacton3ngqa7ix.kinstacdn.com/wp-content/uploads/2015/10/Gap-Analysis-clr_illstrtn.png

2 - Doesn't convey a sense of time and a depiction of people isn't relevant for our case, but visceral conveys how situation is untenable 
 https://americanprinter.com/images/Believe_-_Unseen_-_Opportunity_revised.png

3 - Like how this conveys both the contributing factors to divergence, but also how convergence would be achieved
https://www.slideteam.net/media/catalog/product/cache/1/thumbnail/543x403/0e7a751fc24f39b632cb88e6c5925d9b/m/a/market_convergence_and_divergence_powerpoint_slide_ideas_Slide01.jpg

4 - Similar to #3, but only depict contributing factors to divergence - not convergence
https://www.inflexion-point.com/hs-fs/hubfs/Value%20Gap%20diagram%20V4.png?t=1538325272726&width=320&name=Value%20Gap%20diagram%20V4.png

**Comment by thedavidprice** [comment]
closed via #20
