### ISSUE TITLE
Improve Banner Title

### ISSUE THREAD

**Issue by grwim** [grwim/grwim.github.io#6]
banner title isn't working: too vague & confusing, lacks clarity about what ACRO does in one short sentence.
- propose "A trusted facilitator of policy for the operation of cloud-connected robots"
- Karl, is there any other word or concept for "policy"... an idea to wrap all this in?
- check out the section "The Way Forward" on this page: http://humanetech.com/problem#the-way-forward Note there "4 levers", which feels like we can use this structure and include "policy" as one a several levers

**Comment by thedavidprice** [comment]
Per email with Karl, here’s the plan:

**Banner Headline:**
We facilitate agreements, best practices, standards and other policy essential to realizing the potential of cloud-connected robots.

It’s a long sentence, so will need to work on typography to maximize readability: size, weight, padding on left and right when full-screen desktop. Also will need to make sure tagline below is visually distinct and enough space between to not get lost in the sentence.

**Comment by thedavidprice** [comment]
closed via #20
