### ISSUE TITLE
Andrew-specific Issues

### ISSUE THREAD

**Issue by grwim** [grwim/grwim.github.io#9]
Can update completion as takes place in #5 

**High Priority**
- [ ] in menu, "Stakeholders" styling and size should match problem and solution
- [ ] need padding above "Robotics has a dirty little secret:"
- [ ] who should join section: doesn't read well (both styling and layout issue), let's just make the 4 items a centered, bullet point list
- [ ] images aren't working: too literal, and "cool" tones convey different emotions than we want, banner makes shape of heart sign which doesn't fit message, two-fingers touching like God/Adam implies philosophical statement. short-term: pattern or generic background possible? better to not have strong images than to mis-communicate with the incorrect images

**Layout and Styling**
- [ ] ~~padding between sections and text is inconsistent~~
- [ ] ~~text styling: improve typography for better readability (especially within sections) -- standardize and padding~~
_dsp edit: these are a lower priority to be completed at another time._

**Comment by thedavidprice** [comment]
Moved this one into PR to simplify project management
